services:
  postgres:
    image: postgres:15-alpine
    container_name: employee-management-postgres
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - employee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d employee_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-management-app
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - employee-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  employee-network:
    driver: bridge